version: '3.9'

services:
  web:
    image: php:8.2-apache
    container_name: php8.2-apache
    ports:
      - "8081:80"
    volumes:
      - ./app:/var/www/html/
    environment:
      TZ: Asia/Jakarta
    depends_on:
      - db
    restart: always
    networks:
      - webnet

  db:
    image: mariadb:10.5
    container_name: mariadb
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: root
      MYSQL_USER: root
      MYSQL_PASSWORD: root
    volumes:
      - ./mysql:/var/lib/mysql
    restart: always
    networks:
      - webnet

  adminer:
    image: adminer:4.8
    container_name: adminer
    ports:
      - "8082:8080"
    depends_on:
      - db
    restart: always
    networks:
      - webnet

networks:
  webnet:
    driver: bridge